### ISSUE TITLE
Evaluation module has strong dependency on numpy 1.x.x; update to be agnostic and allow using numpy 2.x.x

### ISSUE THREAD

**Issue by amithjkamath** [rundherum/pymia#52]
Hey @fabianbalsiger - at the MIA lab lecture today, @tinasalvisberg caught this issue: 

Traceback (most recent call last):
  File "C:\Users\tinas\PycharmProjects\mialab\pipeline.py", line 199, in <module>
    main(args.result_dir, args.data_atlas_dir, args.data_train_dir, args.data_test_dir)
  File "C:\Users\tinas\PycharmProjects\mialab\pipeline.py", line 126, in main
    evaluator.evaluate(image_prediction, img.images[structure.BrainImageTypes.GroundTruth], img.id_)
  File "C:\Users\tinas\anaconda3\envs\mialab\lib\site-packages\pymia\evaluation\evaluator.py", line 144, in evaluate
    distances = pymia_metric.Distances(prediction_of_label, reference_of_label, get_spacing())
  File "C:\Users\tinas\anaconda3\envs\mialab\lib\site-packages\pymia\evaluation\metric\base.py", line 312, in __init__
    self._calculate(prediction, reference, spacing)
  File "C:\Users\tinas\anaconda3\envs\mialab\lib\site-packages\pymia\evaluation\metric\base.py", line 412, in _calculate
    distmap_pred = np.Inf * np.ones(borders_pred.shape)
  File "C:\Users\tinas\anaconda3\envs\mialab\lib\site-packages\numpy\__init__.py", line 414, in __getattr__
    raise AttributeError(
AttributeError: `np.Inf` was removed in the NumPy 2.0 release. Use `np.inf` instead.

It appears line 412 (https://github.com/rundherum/pymia/blob/22f8e0962a308236ab2194b4a93e3e9f512949c1/pymia/evaluation/metric/base.py#L412) and many other instances use np.Inf which was removed in numpy 2.0. Could this be updated to use "inf" instead? 

Happy to make this change in a PR if you prefer, but thought I'll post it here in case you have other ideas prior to me doing this.

Amith

**Comment by fabianbalsiger** [comment]
Hi Amith

using `np.inf` sounds good. Thanks for providing a PR!

Best,
Fabian

**Comment by amithjkamath** [comment]
Here you go! https://github.com/rundherum/pymia/pull/53 :-) 

Thanks!

**Comment by fabianbalsiger** [comment]
Merged and published v0.3.4. Thanks for contributing!
